# -*- mode: org -*-
#+TITLE: η Expansion
#+DATE: 2046-01-07T11Z
#+AUTHOR: Alice M. Lorenz

* Abstract

　冬休みの3日めの夜。しんしんと降り続ける粉雪で、
道路が粉砂糖をかけたココアケーキみたい。
イルミネーションで豪勢に飾られたクリスマスツリーのために
道路は昼間のように明るい。

　仕事で疲れた社会人や
勉強をこなした学生が、みんな、帰りの電車に乗るために
京都駅へ吸い込まれるように集まり、
ちょうどお風呂の栓を抜いたときにできる渦巻きのような
流れをつくっている。

　そんななか、わたしは、京都駅から離れるようにして、
人の流れに逆らうようにして歩いている。

　目的地は京都λ抽象学院だ。

　なぜ、ほかのだれかではなく、よりにもよってこのわたしが
冬休みの3日めに学校へ出向くのかというと、
学校のわたしの住んでいる寮に設置されたサーバに、
昨日の昼頃、何者かが不正にログインし、Facebook Searchという
検索エンジンのTCPパケットを改竄してsearch.facebook.comドメイン以下の
すべてのページにマルウェアへのリンクを張ったからだ。

　量子コンピュータでTLSが無力化し、
HTTPSやSSHが無効化されているとはいえ、
そんなに簡単にページの改竄ができるものなのだろうか。

　ともあれ、京都λ抽象学院のルータを通して通信していたたくさんの
〈マシン〉がそのマルウェアに感染したことは事実としてあるらしく、
今日の午後それが発覚して、まず最初に疑われたのが、その
寮に住んでいる、わたしと、ソフィーヤと、真鳥の3人だったわけだ。

* Introduction

　2045年12月23日土曜日午後7時前。わたしは京都駅からバス停へ向かう。

　バス停でソフィーヤが待っていた。彼女はロシア人だから
寒さには強いと思ってたけど普通に厚着をしていた。

　わたしはカーディガンのポケットに両手を突っ込み、震えながら
彼女を見上げてたずねる。

「ロシア人はこの時期でも薄着かと思ってたけど」

　ソフィーヤは表情を変えず冷静に答える。

「アリス、ロシアはシベリアじゃない……モスクワの気温は……たぶん
ザールラントと変わらない」

　アリスことわたしはドイツのザールラント出身。
ソフィーヤはロシアのモスクワ出身。ふたりとも留学生。

　わたしとソフィーヤは京都府に住んでいるから待ち合わせられたけど、
真鳥は兵庫県に住んでいるから時間がかかる。

　それにしても、こんな時間に兵庫県から呼び寄せるなんて、
後藤先生も鬼畜だと思う。

　わたしはぼそっとつぶやく。

「真鳥はたいへんねぇ……ひょっとして今日は帰れないんじゃないかしら」

　ちらっとソフィーヤの顔を見ると、彼女の〈眼鏡〉には
メールが表示されていた。彼女はメールを読みながら冷徹にも答える。

「寮があるから平気だと思う」

　バスが来たので、わたしとソフィーヤはバスに乗る。

　ソフィーヤは無言でなにかメールをしているみたい。

　わたしは唇を尖らせてそっぽを向いてたずねる。

「なに読んでるの」

　一緒にいるときにメールを読まれてると、
なんだか無視されてるみたいで。

　ソフィーヤは答える。

「後藤先生に質問してる……というのも……どこまで
わかってるのか……掴んでおきたいから」

「サーバに侵入した犯人のこと？」

「そう……」

「ふん。悪いのは学院よ。セキュリティを怠ったのが悪いのよ」

「学院のセキュリティは……かなりしっかりしてると思うけど……」

「思う？　現在形？　わたしたち、意見が合うのね、わたしも
思っていたわよ——過去形であることに注意ね！——侵入された事実はないわ、
フィクションよ！　そうに違いないわ」

「……そうじゃないと思う……問題があったのは学院じゃなくて……むしろ生徒……」

「あらそう。なにか心当たりでも？」

　ソフィーヤは黙って目をうろうろさせ、うつむいてしまう。

　わたしはびっくりして思わずたずねる。

「……ほんとにあるの？」

「わたし……一昨日……サーバにログインしてた……リモートで……SSHで……」

　わたしは耳を疑う。ソフィーヤが？　サーバに？　ログイン？　リモート
で？　SSHで？

　……量子コンピュータは市販されている。SSHはほとんど信用ならない、
ログインするならLANでのみ、そう授業で習ったはず。

　SSHは、TLSという——SSLとも呼ばれる——技術に基づいている。

　そしてTLSは、公開鍵暗号——たとえばRSA暗号——に基づいている。

　公開鍵暗号というのは、非対称暗号とも呼ばれていて、
共通鍵暗号——対象暗号——と対をなす暗号システムのこと。

　共通鍵暗号というのは、たいへんわかりやすくて、
2つのノードの間で同じ鍵を用意して、同じアルゴリズムで
暗号化と復号をする方法。

　ところが、共通鍵暗号には、問題がある。
それは、暗号化に使う鍵をどうやって交換するのかということ。
鍵そのものを通信して渡してしまうと、鍵そのものを
盗聴されたら、その鍵を使って暗号化した通信も
復号できてしまうので、意味がない。

　その問題を、きれいとは言えないまでも、
現実的に解決するのが、公開鍵暗号という方法。

　公開鍵と秘密鍵は、ちょっとわかりにくいけど、
“公開鍵で暗号化したものは秘密鍵でしか復号できず、
秘密鍵で暗号化したものは公開鍵でしか復号できない”
という性質を持つ鍵のペアのこと。

　公開鍵暗号では、まず、
暗号化したデータを受信するノードが、
公開鍵と秘密鍵のペアを生成する。それから、
暗号化したデータを受信するノードが、
暗号化したデータを送信するノードに、
公開鍵を渡す。

　このとき、公開鍵は盗聴される可能性があるけど、
秘密鍵はどこにも送信していないので盗聴される可能性がないことに注意して。

　ちょっと、この状況を整理すると、

1) 暗号化したデータを受信するノードは、秘密鍵を持っていて、
2) 暗号化したデータを送信するノードは、公開鍵を持っていて、
3) 公開鍵は、攻撃者に盗聴されている可能性があり、
4) 秘密鍵は、攻撃者に盗聴されている可能性はない

ということになる。

　ここで、暗号化したデータを送信するノードが、
暗号化したデータを受信するノードへ、
公開鍵でデータを暗号化し、送信する。

　公開鍵で暗号化したものは秘密鍵でしか復号できないから、
この暗号化されたデータは、たとえ盗聴できたとしても、
秘密鍵を持っているノードしか復号できない。

　つまり、暗号化したデータを受信するノードしか、
このデータを復号できない。

　こうすることで、

1) 通信で公開鍵を送信しつつ、
2) その公開鍵で暗号化しても安全

　という要件を満たせている。

　ただ、公開鍵と秘密鍵のペアがひとつだと、まだ一方通行の
通信しかできない。

　公開鍵は盗聴されている可能性があるから、
秘密鍵で暗号化しても、盗聴された公開鍵で復号される
可能性がある。

　でも、2つのノードがお互いに公開鍵と秘密鍵のペアを生成しあって、
それぞれの公開鍵を交換すれば、問題なく通信できる。

　SSHは、安全にリモート・ログインするためのプロトコルで、
公開鍵暗号で鍵を暗号化して交換し、
その鍵で通信を暗号化することで安全に通信することができた。

　ややこしいけど……つまり、通信自体は共通鍵暗号で暗号化されている
んだけど、最初に通信するときの鍵の交換だけは公開鍵暗号で
暗号化しているってわけ。

　どうしてこんなややこしいことをするのかというと。
公開鍵暗号は強力だけど性質上復号に時間がかかるので、
毎回公開鍵暗号で暗号化してたらインタラクティブに処理できない。
そのため、鍵だけを公開鍵暗号で暗号化して送信し、
あとは共通鍵暗号で済ませるってこと。

　RSA暗号は、代表的な公開鍵暗号で、
素数と素数を掛け合わせて合成数を求めるのは簡単だけど、
合成数を素因数分解して素数と素数を求めることは難しいことを
根拠としている。

　たとえば、2048ビット長のRSA暗号を素因数分解で
解読するには、3×10^{20}年の時間が必要とも言われていた。

　もっとも、この時間は古典コンピュータの進化とともに短くなっていく
んだけど。

　とはいえ、20年から30年前の古典コンピュータの時代では、
RSA暗号はとても頑丈な暗号だった。

　でも、量子コンピュータが登場した。

　量子コンピュータは、ショアのアルゴリズムを使って、
素因数分解を高速に——たとえば2048ビット長のRSA暗号を
ものの数秒で——処理できた。

　するとどうなったか。 RSA暗号は安全とは言えなくなって
しまった。 なぜなら、もともと RSA 暗号が安全な根拠は、
大きな整数の素因数分解に 3×10^{20}年かかるからであって、
暗号化が絶対不可能というわけではなかったのに、
それがものの数秒で解けるようになってしまったから。

　SSH が安全な理由である、鍵の交換を公開鍵でするという
部分が、危険になってしまった。

　長々しくなったけど、要は、 SSH でリモート・ログインすると、
盗聴されて、公開鍵暗号で暗号化したはずの共通鍵暗号の鍵が
解読される危険性がある。そして、その鍵が解読されれば、
通信自体がすべて復号できる。すると、その情報をもとに
TCPセッション・ハイジャックが可能となり、その結果、
攻撃者のサーバへのログインを許してしまう。

　とまあ、こういうわけで、SSHでリモート・ログインすることは
校則で禁止されてる。

# 　いろいろ問題があるんだけど、SSHでリモート・ログインすることは
# 危険なので校則で禁止されてる。

　でも、リモート・ログインは便利だから、ついつい使ってしまう。
盗聴される危険性があるのもわかるけど、
きっと、わたしだけは大丈夫だろう、そんな気持ちでみんな
使ってしまうんだ。

　わたしは確認する。

「ほんとなの……？」

　ソフィーヤはうなずく。

　鳥肌が立つ。緊張する。

　つまり、その、本当に原因はソフィーヤで、
秘密鍵が解読されて、パスワードが盗まれたってこと？

　もちろん犯人は別にいるとはいえ、そんな事実が発覚したら、
ソフィーヤはどうなるか。退学？　よくて停学？　サーバは
処分されるかも。同じ寮のわたしたちは？　どうなるかわからない。

　これから先の学校生活が破壊される。

　こわい。

　わたしは指をこねくり合わせて目を逸らし、たずねる。

「どっ、どうしてサーバにリモート・ログインしたのかしら」

「それはその……とあるファイルをサーバから〈マシン〉に
コピーし忘れてたから……」

　とあるファイルがなんであるかは、たずねないほうがいいだろう。

　わたしはしどろもどろで言う。

「そう、残念、だわ……」

　バスが荒神口通りに着く。

　わたしとソフィーヤはそこで降りて、学校まで歩く。

　夜中の学校の、職員室の窓だけが光っている。

　わたしは門でインターホンを押す。

　インターホンのディスプレイに後藤先生の顔が写り、
彼女はおごそかに言う。

「いま、鍵を開けました。どうぞ入ってください」

　わたしとソフィーヤは学校のなかに入り、
職員室へ向かう。

　職員室の扉を開けると、温暖な空気が漏れ出てきて、
なかに入ると、眼鏡があっという間に曇る。

　わたしとソフィーヤは眼鏡を一度外し、結露を拭いてから
再度身に付ける。

　職員室には後藤先生——わたしたちの担任——以外の先生はいない。

　わたしたちは後藤先生の机まで行く。

　後藤先生はしかめっ面で椅子に座っている。

　後藤先生がふだん通りの優しい口調で言う。

「どうぞ、空いている席はたくさんあります。お座りください」

　ソフィーヤは黙って言うとおりに座る。

　わたしはある椅子に座る前に高さを調節してから——つまり、
悔しいけど座席部分を可能な限り高くしてから——その椅子に座る。
それでもやや低過ぎる気がして悔しい。

　ソフィーヤがわたしを気遣ってくれたのか、何気なく言う。

「なんなら……わたしの膝の上に座っても……」

　わたしは顔が真っ赤になる気がした。
そういうことはその、ふたりきりのときなら嬉しいけど、
いまは後藤先生の前だし……。わたしはそっぽを向いて抗議する。

　後藤先生の〈眼鏡〉にウィンドウが表示されている。
どうやらメールしているみたいだ。

　後藤先生は指でたんと机を叩くような仕草をする。
〈指輪〉——ブレイン・マシン・インターフェイスの一種で、
指の神経への電気信号を理解し、空中でも机でもどこでも、
タップすることでクリックやダブルクリックができて、
指で空をなぞることでマウスポインタを動かせる、
マウスに代わる入力デバイス——を操作しているのだ。
その操作で、彼女は眼鏡に表示されたウィンドウを閉じ、
言う。

「真鳥さんはあと17分ほどで到着するようです。
真鳥さんが来てからまた話すことになるのは時間のムダですし、
詳しい話は彼女が到着してからにしましょう」

　ソフィーヤが即座に答える。

「賛成……です……」

　わたしは質問する。

「それまではどうします？」

#+BEGIN_COMMENT

「そうですね……では、いくつか出題します——今回の件にも関係のある
ことです——あなたたちが授業で習ったことをしっかり身につけられているか
どうか、抜き打ちテストです」

　ソフィーヤは眉ひとつ動かさないけど、わたしは心のなかで
思わず（ヒーッ）と叫んでいたし、たぶん顔にも出ていたと思うと、
恥ずかしくなる。

　後藤先生はにっこり笑う。

「答えられなくてもかまいませんよ。公式な
問題ではないし、成績には影響しませんので」

　わたしは冷や汗をかく。答えられる自信はほとんどない。

「それでは最初の問題です」と、後藤先生が切り出すが、
「あっと、えっと、その前に……前提を共有しましょう。
一昨日——12月21日、冬休み初日ですね——、ソフィーヤさんは、
自宅からSSHで件のサーバにリモート・ログインした。
これは本人の証言です。これはあとで真鳥さんにも話すつもりですが、
アリスさんは、この事実をご存知ですか？」

「はい、道中、ソフィーヤから聞きました」

「ここから出題。まず、SSHとはなにか。簡潔に述べよ」

　選択問題じゃない！　選択なら消去法とかいろいろ
解き方の定石があるのに。こういう問題は苦手だ。

　そう思っていると、ソフィーヤがすらすらと答える。

「SSHは……およそ15年ほど前まで使われていた……安全にリモート・マシンと
通信するためのプロトコルです……」

「正しい。では次の問題。SSHによるリモート・ログインは、現在
危険だと考えられている。それはなぜか」

　わたしは授業で習った記憶を引っ掻き回す。
たしか、量子コンピュータでショアのアルゴリズムがなんとかとか……。

　そうこう考えているうちに、ソフィーヤが答えてしまう。

「……量子コンピュータ」

#+END_COMMENT

* Methods

* Results

* Discussion

* Conclusion
