# -*- mode: org -*-
#+TITLE: 2045-04-05-T05Z
#+DATE: 2045-04-16-T10Z
#+AUTHOR: Kozonoi Matori

* Abstract

　京都λ抽象学院の入学式を終えたわたし。

　でも、それで終わりではありません。

　同日——つまり今日——京都λ抽象学園の入寮式があります。

　入寮式は、入学式よりも大事な式。

　これから1年間同じ寮で暮らす友達が決まるんだから。

　どんな友達と一緒になれるかな。

　デリアと一緒だったらいいな、なんて思いながら、
わたし、古園井真鳥は、京都λ抽象学院の入寮式を迎えるところです。

* Introduction

　わたしは、数時間前、京都λ抽象学園の入学式を終えたところです。

　今日出会った2人の女の子。

　緑川コーデリア——Ada が好きな赤毛で緑色の目をした女の子。

　キャット・ウォーターリリィ——Haskell が好きなアルビノの女の子。

　担任の先生は後藤写理先生——Haskellの先生。

　わたしは、ウォーターリリィさんとは一言も話してなくて、入学式の新入生紹介で
見かけただけ。

　でも、彼女の特徴的な容姿は、わたしに強い印象を与えた。

　ウォーターリリィさんはつむじからつま先まで真っ白で、
まるで中世期に彫られた彫刻みたい。

　デリアとわたしはバスで隣りの席になって、
それがきっかけで友達になった。

　いや、それはわたしが一方的にそう思っているだけかもしれない
けど、すくなくともわたしはそう思ってる。

　デリアは話しやすい子だった。

　入学式のあと、教室ですこし話してみて、わたしは彼女と
仲良くなれると確信した。

　それから入寮式。

　入寮式が済んだあと、寮の仮分けがおこなわれます。

　寮は1部屋を3人で共有する。これから1年間一緒の
部屋に住むのだから、だれでも、できれば仲のよい友達と
一緒になりたい。

　だから、寮の組み分けは慎重におこなわれます。

　具体的には、今日、4月5日水曜日の仮分けと、
来週、4月10日月曜日の本分けの2回に分けておこなわれます。

　今日は寮の仮分けで、とりあえずでたらめに決まった生徒と一緒の寮で
2日過ごす。

　生徒は、もし相性の悪い寮生と一緒になったりしたら、今週の
金曜日までに申告すれば変えてもらえます。

　また、反対に、だれだれと一緒の寮がいいなどの希望があれば、
同じように金曜日までに申告すれば考慮してもらえます。

　通常は土日も寮で暮らすけど、今週末の土日だけは実家に帰ります。

　それから、生徒の申告をもとに、週明けに改めて分けられます。

　もし仲のいい3人で意見を一致させて希望できれば、あらかじめ
仲良くなった友達と寮生活を始めることができます。

　わたしは、デリアと一緒の寮に暮らしたい。

　それから、あと1人の友達を探して、一緒になってもらえるよう
説得できればいいな。

　もちろん成功するとは限らないけど、わたしは、
まずはそれを目指しているのでした。

* Methods

　2045年4月5日の午後2時。

　日が傾き始め、やや涼しくなってきました。

　12時くらいまでは暖かくても、昼過ぎからはどんどん気温が下がって、
肌寒くなってくるので、わたしは上着を着る。

　いまはお昼の休憩時間。わたしとデリアはデリアの机の前でお話を
楽しんでいます。

　あと10分もすれば入寮式のためにみんな集まるでしょう。

　デリアはうとうとしていて、目がとろんとしていて、
とっても眠そう。

　わたしはたずねる。

「デリア、眠いの？」

　デリアは答える。

「うん。低血圧なんだ。食後はいつもこう」

「つらそう」

　デリアは耐えられずに机に突っ伏して言う。

「5分寝る」

　わたしはちょっと残念に思いながらも、囁くように言う。

「おやすみなさい」

　友達と話しているときはオフラインでいるのがわたしの
私的なルール。

　でもそうじゃないときはインターネットで暇つぶし。

　わたしは左手の小指で空中をタップしてコネクションをつくる。

　すると、眼鏡の右上の隅にアクセスポイントが表示される。

　この教室の LAN だ。わたしはこの教室には LAN があることに気づいた。

　わたしのポケットに入っているマシンには IPv6 で
グローバルIPアドレスが振られているので、
インターネットに接続するのに LAN は必要ない。

　でも、インターネット——巨大なWAN——と LAN では、できることが違う。

　インターネットでは、他人の名前や年齢などの個人情報にアクセスすることは、
その人が露出狂でない限りは、できないことが多い。

　でも、 LAN の場合、名前や年齢などの個人情報にアクセスできることも多い。

　これは技術的な問題ではなくて、むしろ人間の心理とか、
社会的な理由。

　というのも、 LAN は学校や教室などの限られた範囲でしか接続できない。

　対して、インターネットは、世界中のどこからでも接続できる。

　情報を公開する範囲を限定したいと考えれば、自然と、
LAN では公開するが WAN では公開しない、といった選択をすることになる。

　SSL 全盛の時代ならいざ知らず。

　量子コンピュータで RSA 暗号の安全性が崩れて、 HTTPS も SSH も
危険なプロトコルと考えられている現代で、 WAN で情報を
やり取りするなんて危ないことをしたいと思う人は少ない。

　逆に言うと、 WAN では公開されていなくても、 LAN では
公開されている情報があるかもしれないということ。

　わたしはきょろきょろ教室を見渡す。

　教室の廊下側のいちばん後ろの席を見れば、
そこにはあのアルビノの女の子ウォーターリリィさんが。

　わたしは彼女が LAN で公開している情報がなにかないか
見てみる。

　左手の小指で空中をタップすれば、彼女の個人情報に
アクセスできる。彼女が LAN で公開していればだけど。

　表示されたのは、名前や年齢、性別、国籍など。

　それに Haskell のコードもいくつか公開してるみたいだった。

　古典的なパーサコンビネータライブラリを自作して公開してるみたい。　

　気になっていたので、この際話かけてみようかな、
なんて思っていると、異常なのはウォーターリリィさんだけでは
ないことに気づいた。

　彼女があまりに目立つので気づかなかったけど、彼女と話している
女の子も外国人だ。

　彼女の前の席で、椅子に反対向きに座り——つまり、背もたれを両腕で
抱えるようにして、ウォーターリリィさんのほうを向いて——ウォーターリリィ
さんと話している女の子。彼女は赤いカチューシャをしたブロンドだ。
身長は140cm前半くらい？　デリアより低くて、小学生にすら見える。
その金髪は足元に届くほど長く、量が多くて小さな背中を覆い隠すほど
広がっている。気をつけて歩かないと踏んづけちゃいそう。
邪魔じゃないのかな。

　彼女も LAN で名前を公開している。 Alice-Mechthild Lorenz さんと
言うらしい。でも日本語でも英語でもない言語で書かれていてほとんど
読めない。単語のいくつかは知ってる。 von とか見たことある。
ドイツ語かな……。

　興味深い単語もあった。 Standard ML 。 Alice ML 。
彼女はどうやら Alice ML が好きらしい。

　そしてブロンドの女の子の隣りで、両手を背中に回し、ウォーターリリィさんの
ほうを向いて話している女の子。彼女は、まるで黒猫の毛並みように艶やかで
透明な黒髪を持っている。顔の両側の髪を細長く伸ばしたような髪型を
している。身長はわたしと同じくらいかな。肌の白さから日本人ではないことはわかる。

　Софья Мария Ланда́у さん。
キリル文字。読めない。ただラテン文字でも書かれている。
Sophiya Mariya Landau さん。ソフィーヤさん。ロシア人かな。

　キリル文字は読めないけど、ラテン文字で書かれた部分は読める。
Moscow ML 。この子も Standard ML だ。

　びっくりしてわたしは嬉しくなった。処理系が違うとはいえ、 Standard ML
が好きな子を見つけることができた。

　わたしは彼女たちと話してみたくなったけど、いきなり話かける
勇気は、わたしにはない。

　それにしても。ここ日本だよね？

　λ抽象学院って、留学生が多いのかな……。

　そんなことを思っていると、ふいにデリアが話かけてきた。

「外国人組が気になる？」

　わたしは振り向いて思わずたずねる。

「寝てなかったの」

「目をつむってただけだよ、5分じゃ寝れやしない」

　わたしはつぶやく。

「留学生が多いな、とちょっと思って」

「まあλ抽象学院はスーパーグローバル学校だしねぇ」

「スーパーグローバル学校？」

「知らない？」

「うん。初耳」

「自分の入る学校のことくらい調べておかないとダメだよ。
国籍が日本以外の国の学生は授業料の全額または一部の免除を受けれたりするの。
だから外国人も多いんじゃないかな」

「なるほど。だからデリアもここへ？」

「違うよ。わたしは国籍日本だし」

　デリアはつまらなそうに言う。

「心と身体だけじゃなくて国籍もアメリカ人だったらなー、いろいろ得できてた
んだけど」

　わたしはちょっと考えてから答える。

「でも、たとえば、医療費高くなったりしない？」

「よく知らない」

「わたしも、法律のことはよく知らないんだけど……得だけじゃなくて
大変なこともあるような気がする」

「まあ、たしかにね」

　それから、わたしは思っていることをデリアにたずねようか迷う。

　寮のこと。

　デリアと一緒の寮で暮らしたい。

　それは本音なんだけど、なかなか言い出せない。

　考えても見て。学生寮とはいえ、それに2人きりというわけでもない
とはいえ、同棲するわけだよ。

　想像すると顔が火照ってくる。

　そんなことを誘って、変に思われないかしら。

　それが不安だし、べつの不安もある。

　断られたら。

　その可能性もないとは言えない。

　仲良くなったと思っているのはわたしだけかもしれない。

　デリアがわたしと話しているのは、たまたま
そこにいた都合のいい暇つぶし程度のことなのかもしれない。

　そういう不安。

　わたしが誘ったときには、その答えが明らかになる。

　明らかになってしまうのが、こわい。

　良い結果と悪い結果の両方が予想できる。悪い結果のリスクを冒して
収縮させてしまうくらいなら重ね合わせの状態を保ったままにして
おきたい。

　なにもしなければ、すくなくとも現状は変わらない。

　いまの何気ない関係を続けることができる。

　だから、なかなか言い出せない。

　そうこう思っているうちに鐘が鳴る。

　わたしはつぶやく。

「あ……」

　デリアが言う。

「入寮式」

　きっちり鐘がなると同時に後藤先生が教室に戻ってきて、
教室内の生徒に宣告する。

「いまから入寮式です。寮の仮分けが決まりました。
みんな廊下にでてください。みなさんには、廊下で3列に
並んでもらいます。ここで、横1行につき1班です。
つまり、同じ部屋になる生徒の横に並んでくださいということです。
この並び順を寮順と言いますが、λ抽象学院では整列する必要がある
場合は、たとえば災害時にも、原則としてこの並び順で並ぶので
注意深く覚えておいてください。廊下で、わたしが3人ずつ呼ぶ
ので——もっとも、2人の班もありますが——その3人は横に並んで、
それまで呼ばれた生徒の後ろに並んでください」

　生徒は言われたとおりに廊下にでる。

　後藤先生は寮の順に生徒の名前を呼ぶ。

　デリアの名前も呼ばれたけど、わたしの名前は呼ばれなかった。

　仮分けとはいえ、違う寮になるのはちょっと寂しい。

　それから、わたしの名前が呼ばれる。

「古園井真鳥さん」

「はい」

　わたしは、それまでに呼ばれた生徒の後ろに並ぶ。

　同じ部屋になるのはだれかな。

　ちょっとどきどきしながら、次に後藤先生が声を放つのを待つ。

　後藤先生が言う。

「ソフィーヤ・ランダウさん」

　あ。さっきの子だ。

　黒髪の女の子がわたしの隣りに並ぶ。

　黒曜石のように吸い込むような黒い紙。それと反発するかのように
真っ白な肌。キリル文字を使っているからといってそうとは
言い切れないけど、なんとなくロシア人のように思える子。

　ソフィーヤさんがわたしのほうを見てにっこり笑う。

　ずるい。と思った。

　こんなふうに笑顔を向けられたら心まで吸い込まれてしまう。

　そんな笑顔。

　その次の後藤先生が名前を呼ぶ。

「アリス・ローレンツさん」

　赤いカチューシャを女の子が、
ふわふわのブロンドをなびかせ、高貴な足取りでソフィーヤさんの隣りに並ぶ。
もうちょっと身長が高ければモデルにすら見えたと思うけど、
彼女は低身長なので子供にしか見えない。

　これでわたしと同じ寮の子が確定した。
ソフィーヤさんとアリスちゃん。

　偶然なのか、わたしたちはみんな Standard ML が好きだ。

　いや、たぶん偶然じゃなくて、好きな言語を考慮して
先生が組分けしてくれたのだろう。

　こうしてわたしたちは並び、ふたたび体育館へ向かう。

　螺旋階段はかなり幅広で、生徒が3列に並んで歩いてもじゅうぶんに
余りある。

　30人近い1年ζ組の生徒が螺旋階段を降りるときはちょっと
こわかった。

　というのも、螺旋階段は支柱や壁に支えられているようには
見えないのだ。

　建築にはうといけど、こんな造形ではあまり重さに強いようには
思えない。

　螺旋階段を降りながら、アリスちゃんがわたしにたずねてきた。

「ねえ、あなた、もしかして Standard ML が好きなの？」

　わたしはいきなり話しかけられてびっくりして思わず顔を背けてしまう。

# 　螺旋階段は重さに弱いのではないか、なんて心配は杞憂で、
# わたしたちは問題なく
# 昇降口まで送り届けられた。

# 　あの螺旋階段はわりと良い設計になっているのかな。

# 　それとも歩いている女の子たちが軽かったのだろうか。

　昇降口。

　わたしは答える。

「 Standard ML 」

　アリスちゃんは元気よく言う。

「やっぱり！」

　わたしは質問する。

「なんでそう思ったのですか」

　アリスちゃんの代わりにソフィーヤさんがか細い、
聞き取れないくらい高くて小さな声で答える。

「わたしと……アリスは……Standard MLが好きだから……」

　アリスちゃんは彼女の声を覆い隠すように言う。

「だから残りひとりもそうだと思うのは、帰納的な推論じゃない？」

　アリスちゃんは元気のいい子で、
ソフィーヤさんは静かな子みたい。

　体育館の前。1年生がみんな並んでいる。

　入寮式が始まる。

　後藤先生が生徒におだやかに告げる。

「入場するときは、3人1組です。班で一緒に入り、ほかの
班の後ろに並ぶようにしてください。わたしが最初に体育館に入るので、
最初の班はわたしの後ろに並んでください。
3人は足取りを揃えて入場してください」

　新入生が3人1組になって次々と入場して行く。

　わたしたちは、外で待っているので、まだなかでなにが起こっているのかは
わからない。

　それから、わたしと、ソフィーヤさんと、アリスちゃんも
なかに入る。

　足取りを揃えて進もうと思ったけど、アリスちゃんがのろのろしているから
どうしても数歩進んではすこし立ち止まるようにして歩くことになる。

　わたしたちは前の班の後ろに並ぶ。

　それから、全員が入場すると、今度はα組から順に、
1班ずつ呼ばれ、校長先生に入寮許可の言葉を頂き、
生徒はそれぞれいくつかの約束事を宣誓する。

　わたしとソフィーヤさんとアリスちゃんも同じようにする。

　それからいくつかの形式的な儀式を済ませて、
わたしたちは退場する。

　退場したら体育館の前で待っている必要はなくて、
退場した順に教室へ戻る。

　こうして入寮式は終わりました。

* Results

　体育館から離れ、校舎へ向かう、わたしとソフィーヤさんとアリスちゃんの
3人。

　昇降口から入って、廊下を辿る。

　1階の廊下で、のろのろと歩きながらアリスちゃんが自己紹介してくる。

「自己紹介がまだだったわね。わたしはアリス・ローレンツ。
こっちはソフィーヤ・ランダウ。あなたの、名前は？」

　わたしはしどろもどろに答える。

「こっ、古園井真鳥」

　螺旋階段をのぼる。ソフィーヤさんが質問してくる。

「わたしは……Moscow MLを使います……真鳥さんは……主にどの処理系を……？」

「SML#……レコード多相性が好きで」

　ソフィーヤさんは静かに続けて質問してくる。

「ということは……“A Polymorphic Record Calculus and Its Compilation”は
読みましたか……？」

　有名な論文の名前を出されてびっくりしてしまう。わたしは顔を背ける。

「いえ、その……英語は苦手で」

「なるほど……」

　アリスちゃんが蔑むように言う。

「日本人はほんとに英語できないわよね。
とくに冠詞の使い方が下手。“は”と“が”の違いがわからない
日本語学習者みたい」

　ソフィーヤさんが言う。

「ロシア人も……留学したりしなければ……英語も日本語もできない」

　教室に戻る。

　わたしは教室を見渡す。デリアは戻っていたけど、
デリアもデリアで別の友達と話していた。

　なんだか胸がきゅうっと苦しくなる。

　ウォーターリリィさんもいた。

　教室に入るなり、アリスちゃんが駆け出してウォーターリリィさんに抱きつく。

「キャット！　会いたかったわ」

　ウォーターリリィさんは薄いピンク色の唇を動かして答える。

「別れていたのはほんの1時間」

　アリスちゃんはウォーターリリィさんを連れてわたしとソフィーヤの
ところまで来る。

　アリスちゃんが軽快に紹介してくれる。

「紹介するわ。こちらは古園井真鳥さん。仮分けで一緒の部屋になったのよ」

　わたしはびくびく言う。

「よ、よろしくお願いします」

　ウォーターリリィさんは煌びやかに言う。

「よろしくお願いします」

　アリスちゃんは同じようにわたしに紹介してくる。

「こっちはキャット・ウォーターリリィ。
SML じゃなくて Haskeller だから注意してね。
すぐ型クラスでオーバーロードするから」

　ウォーターリリィさんは唇を尖らせる。

「型クラスなしでどうやってモナドを実装するのか」

　ソフィーヤさんが口を挟む。

「SMLにも……functorっていう機能があって——これはHaskellの“F”unctor、
Fが大文字なことに注意してほしい、とは違うけど——こ
れを使えば……モナドのようなものは実装できます」

　わたしは自然と質問していた。

「でも第一級モジュールがないといろいろつらくありませんか？」

　ソフィーヤさんは答える。

「それは……まあ……Successor MLならあるいは……というよりも……
それ以前に……まずRank2Typesがないのがつらいような気がします」

　わたしはなんだか話していて嬉しくなった。
こんなふうに Standard ML の話が通じたことがはじめてだったから。

　ちょっと忘れ気味だったけど、わたしはもともと
Standard ML の話がしたくてここにきた。

　だから、こんな話をもっとしたいと思った。

　ウォーターリリィさんは辛辣に言う。

「というか、モナド以前に、オーバーロードがないと、
たとえばShowのような型クラスがつくれなくて、print_stringとか
print_intとか使い分けないといけないし」

　アリスちゃんは答える。

「たしかにそれは悩みの種ね……SMLでは基本的な四則演算はオーバーロードされ
てるけど……」

　わたしは言う。

「型推論とトレード・オフとはいえ、本音としては型クラスみたいなオーバーロードは
欲しい気がします」

　こんな話をいろいろしてて感じたこと。

　楽しい！

　わたしは、こんな話をもっとしたい。

　とくに Standard ML の話。

　そんなことを思って、しばらくすると、後藤先生が戻ってきた。

　どうやら入寮式はみんな終わったみたい。

　それからしばらくの休み時間をおいて、ホームルーム。
今日は入学式と入寮式だけで、授業はありません。

　全寮制なので、今日と明日は帰らずに寮に泊まります。

　わたしとアリスちゃんと、ソフィーヤさんは、
揃ってはじめての寮に移動。

　デリアは別々だけど、部屋は遠くないので会おうと思えばすぐに
会える。

　でも、わたしとなんだかアリスちゃんとソフィーヤさんと
話すのが楽しくて、デリアのことを考える暇はありませんでした。

　デリアもデリアで、同じ部屋の友達と仲良くやっているみたい。

　嬉しい気もするし、寂しい気もする。

　楽しい気もするし、悲しい気もする。

　そんなことを思いながら、日が落ちて、消灯時間。

　地表はすっかり冷え込んで、寒くて凍えそうなので
毛布にくるまります。

　晴れた夜。雲ひとつない、まるでからすの羽毛のような夜空。

　そんななかにぽつんと光るまん丸の月。

　月明かりがカーテンの隙間から射し込んでいて、電灯を
つけていなくても部屋がしっかり見える。

　これから2日間、わたしたちの住むことになる部屋。

　映画のセットのように広くて整ったキレイな部屋。

　3つのベッドが等間隔で配置されている。

　それぞれのベッドには純白のレースのカーテンが備えられていて、
なかでなにをしているのかは見えないようになっている。

　L字型の机や、豪華なクロゼット、キラキラに輝くキッチン。

　サーバが1台あって、分解したら 256ビット CPU と 16TB のメモリを
備えた、たぶん 30万円くらいはするマシンだとわかったけど、
OS がなにもインストールされていなくて、その代わり Arch Linux や
Gentoo Linux の Live CD があった。わたしたちは、
インストールしようかとも思ったけど、インストールバトルを始めると
寝れなくなるかもしれなかったので、とりあえず今日は保留した。

　大きな本棚には SICP や TCP/IP などの古典的な本がいくつか。

　読んでみたいとも思ったけど、時間がないので、
わたしたちは、やはり保留にした。

　そして、1日が終わります。

* Discussion

　ともあれ、こうして入寮式は終わった。

　今日は Standard ML の話ができて大満足でした！

　アリスちゃん、ソフィーヤさん、そして話してみたかった
ウォーターリリィさんと話せて、いろいろと充実した1日。

　それから、肝心の寮の本分けについてなんだけど。

　とりあえず、仮分けはアリスちゃんとソフィーヤさんが同じ部屋になった。

　でも、まだ寮の仮分けの段階で、わたしとアリスちゃんとソフィーヤさんが
同じ部屋になるというのは、決まったわけじゃない。

　仮分けの前は、デリアと一緒の部屋になりたいと思っていた。

　でも、アリスちゃんやソフィーヤさんと話してみて、
Standard ML の話ができて、すごく楽しかった。

　だから、わりと、このままアリスちゃんやソフィーヤさんと同じ
部屋になっても、いいと思いました。

* Conclusion

　こうしてわたしは入寮式を終えました。

　今日出会った人。

　アリス・ローレンツ——Alice MLを使う元気で小さなブロンドの女の子。

　ソフィーヤ・ランダウ——Moscow MLを使う静かな黒髪の女の子。
大人しいけど、今日出会った人たちのなかでは、いちばん尖ってると
感じたかも。

　ともあれこれで仮分けは終わりです。

　本分けがどうなるのかは、まだわからないけど。

　わたしは、どう転んでも、受け入れられる気がする。

　デリアと一緒になるなら、それはそれで嬉しい。

　アリスちゃんやソフィーヤちゃんと一緒になるのでも、それは
それで楽しそう。

　いずれにせよ、本分けはどきどきわくわくです。
