# -*- mode: org -*-
#+TITLE: η Expansion
#+DATE: 2046-01-07T11Z
#+AUTHOR: Alice M. Lorenz

* Abstract

　冬休みの3日めの夜。しんしんと降り続ける粉雪で、
道路が粉砂糖をかけたココアケーキみたい。
イルミネーションで豪勢に飾られたクリスマスツリーのために
道路は昼間のように明るい。

　仕事で疲れた社会人や
勉強をこなした学生が、みんな、帰りの電車に乗るために
京都駅へ吸い込まれるような流れをつくっている。

　そんななか、わたしは、京都駅から離れるように、
人の流れに逆らうようにして歩いている。

　目的地は京都λ抽象学院だ。

　なぜ、ほかのだれかではなく、よりにもよってこのわたしが
冬休みの3日めに学校へ出向くのかというと、
学校のわたしの住んでいる寮に設置されたサーバに、
昨日の昼頃、何者かが不正にログインし、Facebook Searchという
検索エンジンのTCPパケットを改竄してsearch.facebook.comドメイン以下の
すべてのページにマルウェアへのリンクを張ったからだ。

　でも、たしかsearch.facebook.comはGGH暗号で暗号化されていたはず。

　GGH暗号というのは、格子暗号のひとつ。
格子暗号というのは、古典的な公開鍵暗号や楕円曲線暗号よりも安全な、
耐量子計算機暗号のひとつで、耐量子計算機暗号のうちでは
もっとも主流のもの。

　耐量子計算機暗号を解読しなければ、TCPパケットの改竄はできない。

　search.facebook.comのTCPパケットを改竄するなんてこと、可能なのだろうか。

　ともあれ、京都λ抽象学院のルータを通して通信していたたくさんの
〈マシン〉がそのマルウェアに感染したことは事実としてあるらしく、
今日の午後それが発覚して、まず最初に疑われたのが、その
寮に住んでいる、わたしと、ソフィーヤと、真鳥の3人だったわけだ。

　つまり、犯人は耐量子計算機暗号を解読してしまうほどの
技術力を持った人物ということになる。

　わたしと、ソフィーヤと、真鳥のうちで、そんなことが
できる技術力を持っているとすればソフィーヤだけだ——彼女は
天才だ——けど、ソフィーヤはわたしの親友だし、
そんな悪いことをするはずがない。

　それに、動機だってないだろうし。

　それでも、わたしたちは疑われている。
身の潔白を主張するため、わたしは、いま京都λ抽象学院へ向かっている。

* Introduction

　2045年12月23日土曜日午後7時前。
わたしは京都駅からバス停へ向かっている。

　バス停でソフィーヤが待っていた。彼女はロシア人だから
寒さには強いと思ってたけど普通に厚着をしていた。

　わたしはカーディガンのポケットに両手を突っ込み、震えながら
彼女を見上げてたずねる。

「ロシア人はこの時期でも薄着かと思ってたけど」

　ソフィーヤは表情を変えず冷静に答える。

「アリス、ロシアはシベリアじゃない……モスクワの気温は……たぶん
ザールラントと変わらない」

　アリスことわたしはドイツのザールラント出身。
ソフィーヤはロシアのモスクワ出身。ふたりとも留学生。

　わたしとソフィーヤは京都府に住んでいるから待ち合わせられたけど、
真鳥は兵庫県に住んでいるから時間がかかる。

　それにしても、こんな時間に兵庫県から呼び寄せるなんて、
後藤先生も鬼畜だと思う。

　わたしはぼそっとつぶやく。

「真鳥はたいへんねぇ……ひょっとして今日は帰れないんじゃないかしら」

　ちらっとソフィーヤの顔を見ると、彼女の〈眼鏡〉には
メールが表示されていた。彼女はメールを読みながら冷徹にも答える。

「寮があるから平気だと思う」

　バスが来たので、わたしとソフィーヤはバスに乗る。

　ソフィーヤは無言でなにかメールをしているみたい。

　わたしは唇を尖らせてそっぽを向いてたずねる。

「なに読んでるの」

　一緒にいるときにメールを読まれてると、
なんだか無視されてるみたいで。

　ソフィーヤは答える。

「後藤先生に質問してる……というのも……どこまで
わかってるのか……掴んでおきたいから」

「サーバに侵入した犯人のこと？」

「そう……」

「ふん。悪いのは学院よ。セキュリティを怠ったのが悪いのよ」

「学院のセキュリティは……かなりしっかりしてると思うけど……」

「思う？　現在形？　わたしたち、意見が合うのね、わたしも
思っていたわよ——過去形であることに注意ね！——侵入された事実はないわ、
フィクションよ！　そうに違いないわ」

「……そうじゃないと思う……問題があったのは学院じゃなくて……むしろ生徒……」

「あらそう。なにか心当たりでも？」

　ソフィーヤは黙って目をうろうろさせ、うつむいてしまう。

　わたしはびっくりして思わずたずねる。

「……ほんとにあるの？」

「わたし……一昨日……サーバにログインしてた……リモートで……SSHで……」

　わたしは耳を疑う。ソフィーヤが？　サーバに？　ログイン？　リモート
で？　SSHで？

　
……量子コンピュータは市販されている。だから、SSHの
基盤になっているRSA暗号はすぐに解読されてしまう。まだGGH暗号に対応
していないSSHはほとんど信用ならない、
ログインするならLANでのみ、そう授業で習ったはず。

　SSHでリモート・ログインすると、TCPセッション・ハイジャックされる
可能性がある。だから、SSHでリモート・ログインすることは
危険なので校則で禁止されてる。

　でも、リモート・ログインは便利だから、ついつい使ってしまう。
盗聴される危険性があるのもわかるけど、
きっと、わたしだけは大丈夫だろう、そんな気持ちでみんな
使ってしまうんだ。

　わたしは確認する。

「ほんとなの……？」

　ソフィーヤはうなずく。

　鳥肌が立つ。緊張する。

　つまり、その、本当に原因はソフィーヤで、
秘密鍵が解読されて、パスワードが盗まれたってこと？

　もちろん犯人は別にいるとはいえ、そんな事実が発覚したら、
ソフィーヤはどうなるか。退学？　よくて停学？　サーバは
処分されるかも。同じ寮のわたしたちは？　どうなるかわからない。

　これから先の学校生活が破壊される。

　こわい。

　わたしは指をこねくり合わせて目を逸らし、たずねる。

「どっ、どうしてサーバにリモート・ログインしたのかしら」

「それはその……とあるファイルをサーバから〈マシン〉に
コピーし忘れてたから……」

　とあるファイルがなんであるかは、たずねないほうがいいだろう。

　わたしはしどろもどろで言う。

「そう、残念、だわ……」

　バスが荒神口通りに着く。

　わたしとソフィーヤはそこで降りて、学校まで歩く。

　夜中の学校の、職員室の窓だけが光っている。

　わたしは門でインターホンを押す。

　インターホンのディスプレイに後藤先生の顔が写り、
彼女はおごそかに言う。

「いま、鍵を開けました。どうぞ入ってください」

　わたしとソフィーヤは学校のなかに入り、
職員室へ向かう。

　職員室の扉を開けると、温暖な空気が漏れ出てきて、
なかに入ると、眼鏡があっという間に曇る。

　わたしとソフィーヤは眼鏡を一度外し、結露を拭いてから
再度身に付ける。

　わたしたちは、目が悪いから眼鏡をしているわけではなくて、
この眼鏡はポケットにいれた〈マシン〉のディスプレイになっているのだ。

　また、表示できる情報は〈マシン〉のものだけではなく、
情報にアクセスさえできれば、パソコンのディスプレイのように
なんでも表示できる。

　ただ、冬は暖かい部屋に入るとすぐ曇ってしまうのが難点だ。

　ところで、〈マシン〉というのは、いまの時代ならだいたい
ひとりひとつは持っている、ポケットに入るくらいの小型デバイスのことだ。

　〈マシン〉にも種類はあるけど、たいていのスペックは128ビットCPUか
256ビットCPUで、メインメモリは512GB程度。マシンにはそれぞれ
IPv6 によってグローバルIPアドレスが振られている。
OSはLinuxディストリビューションのいずれかであることが多い。
最近は16キュービットCPUや32キュービットCPUを積んだ〈量子マシン〉も
あるらしいけど、わたしは持っていない。

　〈指輪〉で入力し、〈マシン〉が計算し、〈眼鏡〉が表示し、
〈イヤホン〉が鳴らし、〈嗅覚シール〉がにおわせてくれて、
〈味覚入れ歯〉があじあわせてくれる。

　これは、いまさら説明するまでもないような、当たり前のことだけど。

　ところで、職員室には後藤先生——わたしたちの担任——以外の先生はいない。

　わたしたちは後藤先生の机まで行く。

　後藤先生はしかめっ面で椅子に座っている。

　後藤先生がふだん通りの優しい口調で言う。

「どうぞ、空いている席はたくさんあります。お座りください」

　ソフィーヤは黙って言うとおりに座る。

　わたしはある椅子に座る前に高さを調節してから——つまり、
悔しいけど座席部分を可能な限り高くしてから——その椅子に座る。
それでもやや低過ぎる気がして悔しい。

　ソフィーヤがわたしを気遣ってくれたのか、何気なく言う。

「なんなら……わたしの膝の上に座っても……」

　わたしは顔が真っ赤になる気がした。
そういうことはその、ふたりきりのときなら嬉しいけど、
いまは後藤先生の前だし……。わたしはそっぽを向いて抗議する。

　後藤先生の〈眼鏡〉にウィンドウが表示されている。
どうやらメールしているみたいだ。

　後藤先生は左手の小指でたんと机を叩くような仕草をする。
〈指輪〉——ブレイン・マシン・インターフェイスの一種で、
指の神経への電気信号を理解し、空中でも机でもどこでも、
タップすることでクリックやダブルクリックができて、
指で空をなぞることでマウスポインタを動かせる、
マウスに代わる入力デバイス——を操作しているのだ。
その操作で、彼女は眼鏡に表示されたウィンドウを閉じ、
言う。

「真鳥さんはあと17分ほどで到着するようです。
真鳥さんが来てからまた話すことになるのは時間のムダですし、
詳しい話は彼女が到着してからにしましょう」

　ソフィーヤが即座に答える。

「賛成……です……」

　わたしは質問する。

「それまではどうします？」

「そうですね……では、いくつか出題します——今回の件にも関係のある
ことです——あなたたちが授業で習ったことをしっかり身につけられているか
どうか、抜き打ちテストです」

　ソフィーヤは眉ひとつ動かさないけど、わたしは心のなかで
思わず（ヒーッ）と叫んでいたし、たぶん顔にも出ていたと思うと、
恥ずかしくなる。

　後藤先生はにっこり笑う。

「答えられなくてもかまいませんよ。公式な
問題ではないし、成績には影響しませんので」

　わたしは冷や汗をかく。答えられる自信はほとんどない。

「それでは最初の問題です」と、後藤先生が切り出すが、
「あっと、えっと、その前に……前提を共有しましょう。
一昨日——12月21日、冬休み初日ですね——、ソフィーヤさんは、
自宅からSSHで件のサーバにリモート・ログインした。
これは本人の証言です。これはあとで真鳥さんにも話すつもりですが、
アリスさんは、この事実をご存知ですか？」

「はい、道中、ソフィーヤから聞きました」

「ここから出題。まず、SSHはリモート・サーバと
安全に通信をするためのプロトコルです。
SSHにおける通信の安全は、公開鍵暗号と
共通鍵暗号という暗号技術によって担保されています。
ここで、共通鍵暗号とはどのような暗号技術か、
簡潔に答えなさい」

　選択問題じゃない！　選択なら消去法とかいろいろ
解き方の定石があるのに。こういう問題は苦手だ。

　そう思っていると、ソフィーヤがすらすらと答える。

「共通鍵暗号は……サーバとクライアントで……同じ鍵を使って暗号化をする
方式です……。共通鍵では……同じ鍵で暗号化したものを……
同じ鍵で復号します……。
鍵は……あらかじめサーバとクライアントに同じものを用意しておくか……
通信する直前に一度だけつくって共有するなどの方法で用意されます。
そして……同じ鍵を用意したうえで……その鍵で暗号化したデータを送信し……
受信したデータをその鍵で復号するようにして……通信の安全を担保します……」

「よろしい。この方式では、鍵が漏れないか、アルゴリズムに脆弱性がない
限りは、基本的に絶対安全と言えます。ところが、共通鍵暗号には、ひとつ
重大な問題があります。それはなんでしょう」

　これはわかる！　わたしは手をあげて元気よく答える。

「はいはい！　わたしが答えます。共通鍵暗号は、鍵で暗号化したデータは
安全に通信できますが、鍵そのものをどうやって通信するのかという問題が
あります」

「正解。つまり、もし攻撃者に
鍵の通信そのものが盗聴されてしまった場合、ほかの通信も攻撃者に
復号されてしまうということですね。ところで、
この問題をきれいとは言えないまでも現実的に解決する方法が公開鍵暗号です。
共通鍵暗号が、鍵をひとつしか用意しないのに対して、
公開鍵暗号は、鍵のペアを用意します。その鍵をそれぞれなんと言うでしょうか」

　これもわかる。わたしは続けて答える。

「公開鍵と、秘密鍵です」

「正解。ところで、この鍵のペアにはある性質があります。ここで、
1) 公開鍵で暗号化したものは、どの鍵で復号できるでしょうか。
2) 秘密鍵で暗号化したものは、どの鍵で復号できるでしょうか」

　ちょっとばかにされてるのかとも思うくらい簡単な問題。
わたしは答える。

「公開鍵で暗号化したものは、秘密鍵で復号できます。
秘密鍵で暗号化したものは、公開鍵で復号できます」

　ソフィーヤが落ち着いて付け加える。

「いまの言い方だと……公開鍵で暗号化したものを復号できるのは
秘密鍵だけではないようにも聞こえるけど……実際には……
公開鍵で暗号化したものが復号されるのは秘密鍵を使ったとき、
またそのときにかぎる……秘密鍵で暗号化したものについても
同様」

　わたしは顔を真っ赤にして抗議する。

「わっ、わかってるわよ、それくらい。言わなくてもわかるでしょ」

　ソフィーヤは細い目でわたしを見て言う。

「事例は……ちゃんと列挙しないと……勘違いする人が……いるかも」

　後藤先生が続ける。

「次の問題。共通鍵暗号では、鍵の送受信が盗聴者に知られると、
通信が復号される可能性がありました。ところで、公開鍵暗号は
鍵の送受信はするものの、鍵が盗聴者に知られても、
通信は復号されない仕組みになっています。それは、
どのような仕組みか。簡潔に答えなさい」

　そんなの、わからない。

　わたしが目をまわしていると、ソフィーヤが答える。

「“公開鍵で暗号化したものを復号できるのは、秘密鍵だけ”という性質を
利用します……。サーバとクライアントで……それぞれ公開鍵と秘密鍵のペアを
ひとつずつ生成し……公開鍵だけを交換します——このとき、
公開鍵は攻撃者に盗聴される危険性があるけど、
秘密鍵は攻撃者に盗聴される危険性はないということに注意して
ください——ここで……データを公開鍵で暗号化して送信すれば……
“公開鍵で暗号化したものを復号できるのは、秘密鍵だけ”なのですから……
攻撃者は秘密鍵を知らないのですから……安全というわけです」

「正しい。次の問題。ところで、SSHは安全にリモート・サーバと通信する
ためのプロトコルです。SSHでサーバとクライアントが通信するとき、
SSHは、
- サーバ認証……サーバがハイジャックされていないかの確認
- ユーザ認証……ユーザがハイジャックされていないかの確認
- 共通鍵暗号による通信の暗号化
- 公開鍵暗号による共通鍵暗号の鍵の暗号化
などをして、通信の安全性を保証してくれます。
サーバとクライアントは、それぞれ公開鍵と秘密鍵のペアを
生成して、かつ、あらかじめ公開鍵は交換しておいたものと
して——この公開鍵の交換は盗聴されても問題はありません——SSHが
おこなう手順は、簡単には、
1) クライアントは、ホスト公開鍵で、ランダムなデータを暗号化してサーバに
   送信し、
2) サーバは、そのデータをホスト秘密鍵で復号してクライアントに送り返し、
3) クライアントは、送り返されたデータと、送ったはずのデータが一致するか
   確かめて——公開鍵で暗号化したものを復号できるのは秘密鍵の所有者だけ
   なので、一致すればサーバがハイジャックされていないと確信できるわけ
   です——
4) クライアントは、共通鍵の鍵をつくり、それをホスト公開鍵で暗号化して
   サーバに送信し——この鍵は、やはり公開鍵で暗号化されているので、秘密鍵の
   所有者しか復号できず、通信は安全です——
5) サーバは、クライアント公開鍵で、ランダムなデータを暗号化して
   クライアントに送信し、
6) クライアントは、そのデータをクライアント秘密鍵で復号して
   サーバに送り返し、
7) サーバは、送り返されたデータと、送ったはずのデータが一致するか
   確かめて——公開鍵で暗号化したものを復号できるのは秘密鍵の所有者だけ
   なので、一致すればクライアントがハイジャックされていないと
   確信できるわけです——
8) 晴れてクライアント認証とサーバ認証が完了したので、
   手順4でつくった共通鍵の鍵で通信を暗号化する
という手順を踏むのですが——すいません、簡単にはと言いつつ、
ややこしく、複雑でした——要は、公開鍵暗号で鍵を暗号化して交換し、 
その鍵で通信を暗号化することで安全に通信します。
これを前提として、いくつか出題します。
まず、このとき、公開鍵暗号としては、たいていRSA暗号が使われます。
ここで、RSA暗号はどのような公開鍵暗号か、簡潔に答えなさい」

　ソフィーヤがまるで教科書を暗記しているかのようにすらすらと答える。

「RSA暗号は……代表的な公開鍵暗号で……
素数と素数を掛け合わせて合成数を求めるのは簡単だけど……
合成数を素因数分解して素数と素数を求めることは難しいことを 
根拠としています……たとえば、2048ビット長のRSA暗号を素因数分解で 
解読するには……3×10^{20}年の時間が必要とも言われていました……
無条件安全性はありませんか……計算量的安全性はあるというやつです……」

「正しい。もっとも、その時間は古典コンピュータの進化とともに
短くなっていきます。
ところで、無条件安全性と計算量的安全性とはなにか。簡潔に説明せよ」

　これはわかる。わたしは説明する。

「無条件安全性というのは、解読が不可能という意味です。
鍵の長さが送信するデータと同じかそれ以上の長さであれば、
無条件に安全です。計算量的安全性とは、解読は可能だけど、
古典コンピュータでは解読するのに非現実的なほど長い時間がかかる
ことです。同じアルゴリズムでも、単純に鍵の長さを長くすることで、
計算量的に安全になる可能性があります」

「そう。20年から30年前の古典コンピュータの時代では、 
RSA暗号はとても頑丈な、計算量的に安全な暗号でした。
ところが、RSA暗号の脅威となる技術が現れました。つまり、
ある技術を使うと、RSA暗号の鍵をいくら長くしようとほぼ定数時間で
解読してしまう技術が現れました。それはなにか」

　わたしは授業で習った記憶を引っ掻き回す。
たしか、量子コンピュータでショアのアルゴリズムがなんとかとか……。

　そうこう考えているうちに、ソフィーヤが答えてしまう。

「……量子コンピュータ」

「そう。量子コンピュータで、あるアルゴリズムを走らせると、
素因数分解を高速に——たとえば2048ビット長のRSA暗号を 
ものの数秒で——処理できます。そのアルゴリズムとはなにか」

　わたしは即答する。

「ショアのアルゴリズム」

「そう。するとどうなったか。 RSA暗号は安全とは言えなくなって 
しまいました。 なぜなら、もともと RSA 暗号が安全な根拠は、 
大きな整数の素因数分解に 3×10^{20}年かかるからであって、 
暗号化が絶対不可能というわけではなかったのに、 
それがものの数秒で解けるようになってしまったからです。
ところで、RSA暗号は、SSHの根幹となる暗号です。
当然、SSHも、この影響を受けます。SSHのどの手順がこの
影響を受けるのか答えなさい」

　ソフィーヤがつまらなそうに答える。

「……ユーザの認証と……サーバの認証と……共通鍵の暗号化の部分です……
2048ビットのRSA暗号が主流なので——それが ssh-keygen でつくられる
鍵のデフォルトの形式だからです——それらの部分が、もはや
安全ではないというか、危険です……」

「正しい。では、どのように影響を受けるのか答えなさい」

　ソフィーヤが続けて答える。

「たとえば……まず……攻撃者はホストの公開鍵を入手
します……どうやってホストの公開鍵を入手するのかというと…… ssh
コマンドでホストにアクセスすれば簡単に入手できます……
それから……量子コンピュータでホストの公開鍵からホストの秘密鍵を
計算します……数分もあれば終わるはずです……秘密鍵がわかれば通信の一部が
解読できるようになるので……たとえば、SSHでリモート・ログインするときは、
手順の一部にホストの公開鍵で共通鍵の鍵を暗号化するものがありますが……
このホストの公開鍵で暗号化された共通鍵をホストの秘密鍵で解読することで……
暗号化されたパケットをすべて解読できるようになるので……
TCPセッション・ハイジャックができます……」

　TCPセッション・ハイジャック。あるTCPのセッションになりすます
パケットを横から送信することで、そのTCPを奪ってしまうこと。

　SSHによるリモート・ログインもTCPセッションのひとつだ。

　リモート・ログイン中のTCPをハイジャックする。

　すると、攻撃者はログイン中のセッションを横取りして、
サーバにログインできてしまう。

　それにしても、ソフィーヤはやっぱりすごい。

　理解度が違う。

　わたしが答えられない質問にも、すぐさま答えてしまう。

　ソフィーヤは大人しいけど、すっごく頭がいいってことを再確認した。

　後藤先生はいかめしい顔つきで続ける。声はふんわりしているんだけど、
顔はこわい。

「よろしい。ふたりとも、SSHでリモート・ログインすることがいかに
危険なのかよくわかっているようですね」

　そのとき、職員室にごーんごーんと鐘の音が鳴る。

　インターホンの音。

　こんな時間に来客は来ない。

　どうやら真鳥が到着したみたいだ。

　後藤先生が席を立ち、受話器をとって言う。

「いま、鍵を開けました。どうぞ入ってください」

　廊下から真鳥が入ってくる。彼女は一気に曇る眼鏡を
外すよりも先に、大きく頭を下げて叫ぶ。

「遅れてごめんなさい！　お待たせしました！」

　それから彼女は眼鏡を外し、結露を拭き取りながら、
ふらふらと歩いてくる。

　彼女は目がとても悪く、その眼鏡には度が入っている。

　眼鏡を外すと、そのぱっちりしたまつげがよく目立つ。

　危なっかしい歩き方。

　途中、彼女は腰を机にぶつけて、よろめく。

　腰に届きそうなストレートの黒髪がゆらゆら揺れる。

　彼女は眼鏡をつけながら席に座る。

　わたしは真鳥に挨拶する。

「こんばんは、真鳥」

　真鳥は目をうろうろさせながら答える。

「こんばんは……」

　わたしはいきなりジョークを思いついたので言う。

「良い知らせと悪い知らせがあるわ。どっちから聞きたい？」

　真鳥が指で耳を撫でながらたずねてくる。

「良い知らせから？」

「わたしたちのつくったサーバはなんの問題もなく、すべて正常に動作しているわ」

「じゃあ、悪い知らせって？」

「22番ポートもきちんと動いてたってことかしら」

　22番ポートというのは、sshサーバが普通使うポートのこと。

　真鳥の顔が青ざめる。彼女は耳たぶをいじりながら質問してくる。

「ポートは解放していなかったはず」

　そう。 sshサーバを動かすなら LAN 内でだけ。そう授業で習った。

　sshサーバを WAN 、つまりインターネットに向けて公開したいときは、
ポートを開放する必要がある。

　普通は、危険なのでしない。

　でも、だれかがそれをしてしまった。

　わたしは髪をかきあげて、平静を装いつつ言う。

「それが解放されていたのよ、どういうわけかね」

　そして、それはたぶん、ソフィーヤがやったこと。

　でも、どうして。

　ソフィーヤなら、危険とわかっていたはず。

　なら、なぜ？

　わたしたちの会話に割り込むように、後藤先生がせきをする。

「こほん。みんな集まりましたね。それでは、これから、みんなに集まってもらった
理由を説明します。夜も遅いのでさっさと進めましょう。
質問などがあればいつでもしてください」

　わたしたちは姿勢を正して聞く。

「まず、状況のまとめから入りましょう。
今日の昼頃、何者かがあなたたち3人のサーバに侵入して、
ある本校のルータにログインし、TCPパケットを改竄して
Facebook Searchのすべてのページにマルウェアへの
リンクを張りました。ここまではいいですね」

　ネットワークはルーティングという仕組みによって
成り立っている。ルーティングとは、TCPパケットの通り道のことで、
通常、複数のルータをたくさん繋げたもの。
TCPパケットというのは、ウェブサイトなどの情報を小さな単位に
分割したもの。
TCPパケットはルータからルータへ、バケツリレーのように転送される。
もし、その途中のルータがひとつでも偽のデータを転送して
しまったら？　最終的に届くのは改竄されてしまったページ。つまり、
そのルータが偽のページを転送したことで、
そのルータを通して通信している〈マシン〉がアクセスするページが
改竄されてしまったということ。

　ソフィーヤが質問する。

「その……マルウェアとはいったいなんでしょう……いえ
一般的な単語の意味ではなく……定冠詞をつけた意味で……」

　後藤先生は答える。

「それが、なんなのかまだよくわかっていないのが現状です。
なにしろ、今日の午後発覚したわけですから」

「なるほど……解析は……可能なのでしょうか……」

「もちろん可能でしょうが、なにしろ冬休みでしかも
夜も遅いので関係ない人を働かせるのは後ろめたいものがありまして」

　ていうか、わたしたちはいいのか。まあ関係あると言えばあるけど。

　真鳥が質問する。

「あの、TCPパケットの改竄って、そんなに簡単にできるんですか？」

　後藤先生が答える。

「非常に難しいと思われます。わたしも、専門外なのでよく
わからないんですが……Facebook SearchはGGH暗号で暗号化されていますが、
これはRSA暗号などと違って量子コンピュータでも解読できないはずなので、
現在の技術では、理論上不可能なはずです」

　そう。Facebook SearchはGGH暗号で暗号化されている。
そして、現在、GGH暗号を解読できる方法は存在しない……はず。

　でも、事実できてしまったのだから、その認識は改めないといけない。

「Facebook Searchはみなさん知ってのとおり世界有数のトラフィックを
誇る検索サイトです。犯人の目的は、おそらく大量のトラフィックが
集まる場所でマルウェアを配布することで間違ってダウンロード、
インストール、そして実行してしまった人の〈マシン〉を汚染すること
だと考えられます」

　それはわかる。というか、それ以外に考えられないだろう。あくまで確認。

　後藤先生は続ける。

「これが現在わかっていることです。そして、今日あなたたちを
呼んだ理由は、ふたつあります。ひとつは、あなたたちの潔白を証明する
ためにすこし質問させてもらうこと。ふたつめは、件のサーバを検査して
もらうことです」

　わたしは質問する。

「検査とは、具体的には」

「まず第一に、sshサーバを停止などして、
更なる被害を抑えること。これはわかりますね」

　ソフィーヤが申し訳なさそうに答える。

「はい……」

「第二に、ログなど、犯人に繋がる手がかりがないか
調べること。第三に——これはオプショナルとして、可能なら——ログなどの手がかり
から犯人を突き止めること」

　真鳥が目を丸くして聞き返す。

「犯人を、わたしたちが捕まえるんですか！？」

「できなければ諦めてもいいです。でも、それができれば、
学院およびソフィーヤさんをはじめあなたたちの名誉が回復します。
その功績を、わたしは正式に学校に報告します。
できなければ……やはり、この事件を、わたしは正式に学校に報告します。
そのあとどういう処分がなされるかは、もはや、
わたしの手には負えません」

　わたしはぞくりとする。後藤先生が言っているのは、警告だ。
つまり、なんらかの処分を受けたくなければ、犯人を突き止めてみせろと
言っているのだ。

　後藤先生がおそろしげに言う。

「冬休みが明けるまでは、報告を保留しておきます。
1月7日、日曜日、冬休みの最後の日、
わたしはことの経緯とすべての結果を学校に
報告します。今日、とりあえずsshサーバが停止したことを
確認したら、あとは、わたしは関与しません。
わたしは、選択するために必要な知識をきちんと開示したつもりです。
あとは、あなたたち次第です」

　わたしたち次第。処分を回避できるかどうかは、
わたしたちの行動次第。

　わたしは迷う。今回の件で、いちばん悪い処分を受けるのは、
たぶんソフィーヤ、わたしの親友だ。もし、問題を真鳥が起こしたというのなら、
わたしは自業自得だと言って、今日はさっさと帰っていただろう。
でも、問題を起こしたのはソフィーヤだ。もし、わたしがソフィーヤと
無関係な第三者で、この事件をニュースかなにかで知っていたとすれば、
わたしはソフィーヤの自業自得だと言っていただろう。でも、あろうことか、
焦点は大好きな親友に合っているのだ。

　わたしは、ソフィーヤの助けになってあげたい。

　彼女がどう考えてどういう選択をしたのだとしても、それを
支えてあげたい。

　わたしは決意する。

　わたしは立ち上がって、前にどんと踏み出し、叫ぶ。

「ソフィーヤ、真鳥、わたしについてきなさい！　こんな事件を起こした
不埒ものを突き止めるのよ」

　ソフィーヤが静かに答える。

「わたしはいいけど……真鳥は……」

　わたしは真鳥をぎらりと睨みつける。

　真鳥はびっくりして素っ頓狂な声をあげる。

「もっ、もちろんっ、わたしも付き合いますよ」

「付、き、合、う？」

「いっ、いえ……言葉を間違えました。後学のために参加させていただきます！」

「よろしい」

　真鳥は耳をいじりながらたずねてくる。

「でも、今日は、その、もう帰らないと……終電が……」

「泊まればいいじゃない、寮があるんだから」

「はっ、はい……」

　こうして、わたしたちはサーバを検査し、
メンテし、犯人の痕跡を調査し、また犯人を突き止めるために、
冬休みのあいだ、寮に泊まり込むことになったのだ。

* Methods

* Results

* Discussion

* Conclusion
