# -*- mode: org -*-
#+TITLE: 2045-04-05-T05Z
#+DATE: 2045-04-16-T10Z
#+AUTHOR: Kozonoi Matori

* Abstract

　京都λ抽象学院の入学式を終えたわたし。

　でも、それで終わりではありません。

　同日——つまり今日——京都λ抽象学園の入寮式があります。

　入寮式は、入学式よりも大事な式。

　これから1年間同じ寮で暮らす友達が決まるんだから。

　どんな友達と一緒になれるかな。

　デリアと一緒だったらいいな、なんて思いながら、
わたし、古園井真鳥は、
京都λ抽象学院の入寮式を迎えるところです。

* Introduction

　わたしは、数時間前、京都λ抽象学園の入学式を終えたところです。

　今日出会った2人の女の子。

　緑川コーデリア——Ada が好きな赤毛で緑色の目をした女の子。

　キャット・ウォーターリリィ——Haskell が好きなアルビノの女の子。

　担任の先生は後藤写理先生——Haskellの先生。

　わたしは、ウォーターリリィさんとは一言も話してなくて、入学式の新入生紹介で
見かけただけ。

　でも、彼女の特徴的な容姿は、わたしに強い印象を与えた。

　ウォーターリリィさんはつむじからつま先まで真っ白で、
まるで中世期に彫られた彫刻みたい。

　デリアとわたしはバスで隣りの席になって、
それがきっかけで友達になった。

　いや、それはわたしが一方的にそう思っているだけかもしれない
けど、すくなくともわたしはそう思ってる。

　デリアは話しやすい子だった。

　入学式のあと、教室ですこし話してみて、わたしは彼女と
仲良くなれると確信した。

　それから入寮式。

　入寮式が済んだあと、寮の仮分けがおこなわれます。

　寮は1部屋を3人で共有します。これから1年間一緒の
部屋に住むのですから、だれでも、できれば仲のよい友達と
一緒になりたいものです。

　だから、寮の組み分けは慎重におこなわれます。

　具体的には、今日、4月5日水曜日の仮分けと、
来週、4月10日月曜日の本分けの2回に分けておこなわれます。

　今日は寮の仮分けで、とりあえずでたらめに決まった生徒と一緒の寮で
2日過ごします。

　生徒は、もし相性の悪い寮生と一緒になったりしたら、今週の
金曜日までに申告すれば変えてもらえます。

　また、反対に、だれだれと一緒の寮がいいなどの希望があれば、
同じように金曜日までに申告すれば考慮してもらえます。

　通常は土日も寮で暮らすけど、今週末の土日だけは実家に帰ります。

　それから、生徒の申告をもとに、週明けに改めて分けられるのです。

　もし仲のいい3人で意見を一致させて希望できれば、あらかじめ
仲良くなった友達と寮生活を始めることができます。

　わたしは、デリアと一緒の寮に暮らしたい。

　それから、あと1人の友達を探して、一緒になってもらえるよう
説得できればいいな。

　もちろん成功するとは限らないけど、わたしは、
まずはそれを目指しているのでした。

* Methods

* Results

* Discussion

* Conclusion
